import { Coffee, FlaskConical, Sunset, Waves, type LucideIcon } from "lucide-react";

export type Product = {
  id: number;
  slug: string;
  name: string;
  description: string;
  tastingNotes: string[];
  roastLevel: "Light" | "Medium" | "Dark" | "Espresso";
  origin: string;
  category: string;
  basePrice: number;
  featured: boolean;
  rating: number;
  reviews: number;
  images: string[];
  badge?: string;
  grindOptions: string[];
  weightOptions: number[];
  stock: number;
};

export type BrewingMethod = {
  title: string;
  description: string;
  icon: LucideIcon;
};

/**
 * Coffee photos on images.unsplash.com. These are the same nine photos
 * the live BrewCraft site already serves.
 *
 * To add more photos: append a new Unsplash photo ID to this list, then
 * use its position (0-based) in gallery(...) below.
 */
const PHOTO_IDS = [
  "1497636577773-f1231844b336", // 0
  "1442512595331-e89e73853f31", // 1
  "1504753793650-d4a2b783c15e", // 2
  "1447933601403-0c6688de566e", // 3
  "1461023058943-07fcbe16d735", // 4
  "1559056199-641a0ac8b55e", // 5
  "1521017432531-fbd92d768814", // 6
  "1459755486867-b55449bb39ff", // 7
  "1498804103079-a6351b050096", // 8
] as const;

const unsplash = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=80`;

/** Build an image list from photo positions, e.g. gallery(0, 6, 4). First one is the main image. */
const gallery = (...positions: number[]) =>
  positions.map((position) => unsplash(PHOTO_IDS[position % PHOTO_IDS.length]));

export const products: Product[] = [
  {
    id: 1,
    slug: "ethiopian-yirgacheffe",
    name: "Ethiopian Yirgacheffe",
    description: "Floral, citrusy, and delicately sweet with a tea-like body and sparkling finish.",
    tastingNotes: ["Lemon blossom", "Blueberry", "Cacao nib"],
    roastLevel: "Light",
    origin: "Ethiopia",
    category: "Single Origin",
    basePrice: 26,
    featured: true,
    rating: 4.9,
    reviews: 240,
    images: gallery(0, 6, 4),
    badge: "New arrival",
    grindOptions: ["Whole bean", "Espresso", "French press", "Pour over"],
    weightOptions: [250, 500, 1000],
    stock: 18,
  },
  {
    id: 2,
    slug: "colombian-supremo",
    name: "Colombian Supremo",
    description: "A balanced and caramel-rich cup with layered sweetness and a silky finish.",
    tastingNotes: ["Caramel", "Orange zest", "Toffee"],
    roastLevel: "Medium",
    origin: "Colombia",
    category: "Single Origin",
    basePrice: 24,
    featured: true,
    rating: 4.8,
    reviews: 198,
    images: gallery(1, 7, 3),
    grindOptions: ["Whole bean", "Pour over", "Drip"],
    weightOptions: [250, 500, 1000],
    stock: 24,
  },
  {
    id: 3,
    slug: "blue-mountain-reserve",
    name: "Blue Mountain Reserve",
    description: "Smooth and refined with notes of cocoa, brown sugar, and toasted almond.",
    tastingNotes: ["Cocoa", "Walnut", "Brown sugar"],
    roastLevel: "Medium",
    origin: "Jamaica",
    category: "Espresso",
    basePrice: 32,
    featured: true,
    rating: 4.9,
    reviews: 152,
    images: gallery(2, 5, 8),
    badge: "Premium",
    grindOptions: ["Whole bean", "Espresso", "French press"],
    weightOptions: [250, 500],
    stock: 12,
  },
  {
    id: 4,
    slug: "italian-dark-roast",
    name: "Italian Dark Roast",
    description: "Bold and full-bodied with bittersweet cocoa and a smoky finish for espresso lovers.",
    tastingNotes: ["Dark chocolate", "Molasses", "Smoke"],
    roastLevel: "Dark",
    origin: "Italy",
    category: "Espresso",
    basePrice: 27,
    featured: true,
    rating: 4.7,
    reviews: 186,
    images: gallery(3, 2, 5),
    grindOptions: ["Whole bean", "Espresso", "French press"],
    weightOptions: [250, 500, 1000],
    stock: 28,
  },
  {
    id: 5,
    slug: "hawaiian-kona",
    name: "Hawaiian Kona",
    description: "A smooth, silky cup with almond sweetness and a clean, lingering finish.",
    tastingNotes: ["Almond", "Honey", "Citrus peel"],
    roastLevel: "Medium",
    origin: "Hawaii",
    category: "Single Origin",
    basePrice: 35,
    featured: false,
    rating: 4.9,
    reviews: 130,
    images: gallery(4, 0, 1),
    grindOptions: ["Whole bean", "Pour over", "Drip"],
    weightOptions: [250, 500],
    stock: 11,
  },
  {
    id: 6,
    slug: "french-vanilla-blend",
    name: "French Vanilla Blend",
    description: "Round, creamy, and comforting with vanilla bean, caramel, and soft cocoa depth.",
    tastingNotes: ["Vanilla", "Caramel", "Cocoa"],
    roastLevel: "Medium",
    origin: "Blend",
    category: "Blends",
    basePrice: 22,
    featured: false,
    rating: 4.6,
    reviews: 214,
    images: gallery(5, 7, 8),
    badge: "Best seller",
    grindOptions: ["Whole bean", "Espresso", "Drip"],
    weightOptions: [250, 500, 1000],
    stock: 35,
  },
  {
    id: 7,
    slug: "guatemala-antigua",
    name: "Guatemala Antigua",
    description: "Bright and layered with berry sweetness, citrus, and a clean cocoa finish.",
    tastingNotes: ["Berry", "Citrus", "Cocoa"],
    roastLevel: "Light",
    origin: "Guatemala",
    category: "Single Origin",
    basePrice: 28,
    featured: false,
    rating: 4.8,
    reviews: 142,
    images: gallery(6, 1, 0),
    grindOptions: ["Whole bean", "Pour over", "French press"],
    weightOptions: [250, 500],
    stock: 20,
  },
  {
    id: 8,
    slug: "sumatra-mandheling",
    name: "Sumatra Mandheling",
    description: "Earthy and syrupy with dark chocolate, cedar, and a decadent finish.",
    tastingNotes: ["Dark chocolate", "Cedar", "Plum"],
    roastLevel: "Dark",
    origin: "Indonesia",
    category: "Single Origin",
    basePrice: 29,
    featured: false,
    rating: 4.7,
    reviews: 118,
    images: gallery(4, 3, 2),
    grindOptions: ["Whole bean", "French press", "Espresso"],
    weightOptions: [250, 500, 1000],
    stock: 16,
  },
  {
    id: 9,
    slug: "morning-ritual-blend",
    name: "Morning Ritual Blend",
    description: "Balanced, nutty, and silky with a comforting cocoa finish for everyday sipping.",
    tastingNotes: ["Hazelnut", "Cocoa", "Brown sugar"],
    roastLevel: "Medium",
    origin: "Blend",
    category: "Blends",
    basePrice: 23,
    featured: false,
    rating: 4.8,
    reviews: 266,
    images: gallery(7, 6, 8),
    grindOptions: ["Whole bean", "Drip", "Pour over"],
    weightOptions: [250, 500],
    stock: 41,
  },
  {
    id: 10,
    slug: "decaf-sunrise",
    name: "Decaf Sunrise",
    description: "A mellow cup of cocoa sweetness and toasted almond with zero compromise on flavor.",
    tastingNotes: ["Toasted almond", "Cocoa", "Orange blossom"],
    roastLevel: "Medium",
    origin: "Peru",
    category: "Decaf",
    basePrice: 25,
    featured: false,
    rating: 4.7,
    reviews: 105,
    images: gallery(8, 4, 1),
    grindOptions: ["Whole bean", "French press", "Drip"],
    weightOptions: [250, 500, 1000],
    stock: 22,
  },
  {
    id: 11,
    slug: "brewcraft-espresso",
    name: "BrewCraft Espresso",
    description: "A sweet, syrupy espresso with notes of dark chocolate and red fruit.",
    tastingNotes: ["Red fruit", "Dark chocolate", "Hazelnut"],
    roastLevel: "Espresso",
    origin: "Blend",
    category: "Espresso",
    basePrice: 30,
    featured: false,
    rating: 4.9,
    reviews: 176,
    images: gallery(5, 2, 3),
    badge: "Espresso pick",
    grindOptions: ["Whole bean", "Espresso"],
    weightOptions: [250, 500],
    stock: 18,
  },
  {
    id: 12,
    slug: "kenya-ntima",
    name: "Kenya Ntima",
    description: "Lively and berry-forward with a crisp finish and tea-like elegance.",
    tastingNotes: ["Berry", "Grapefruit", "Black tea"],
    roastLevel: "Light",
    origin: "Kenya",
    category: "Single Origin",
    basePrice: 31,
    featured: false,
    rating: 4.8,
    reviews: 144,
    images: gallery(1, 6, 7),
    grindOptions: ["Whole bean", "Pour over", "Drip"],
    weightOptions: [250, 500, 1000],
    stock: 14,
  },

  // ---------------------------------------------------------------------------
  // New single origins
  // ---------------------------------------------------------------------------
  {
    id: 13,
    slug: "rwanda-bourbon",
    name: "Rwanda Bourbon",
    description: "Sweet and sparkling with red apple, hibiscus, and a clean, juicy finish.",
    tastingNotes: ["Red apple", "Hibiscus", "Raw honey"],
    roastLevel: "Light",
    origin: "Rwanda",
    category: "Single Origin",
    basePrice: 27,
    featured: false,
    rating: 4.8,
    reviews: 96,
    images: gallery(0, 6, 1),
    grindOptions: ["Whole bean", "Pour over", "Drip"],
    weightOptions: [250, 500],
    stock: 19,
  },
  {
    id: 14,
    slug: "costa-rica-tarrazu",
    name: "Costa Rica Tarrazú",
    description: "Honeyed and crisp with stone fruit sweetness and a bright, polished finish.",
    tastingNotes: ["Peach", "Honey", "Milk chocolate"],
    roastLevel: "Medium",
    origin: "Costa Rica",
    category: "Single Origin",
    basePrice: 26,
    featured: false,
    rating: 4.7,
    reviews: 128,
    images: gallery(1, 4, 7),
    grindOptions: ["Whole bean", "Pour over", "Drip", "French press"],
    weightOptions: [250, 500, 1000],
    stock: 30,
  },
  {
    id: 15,
    slug: "brazil-santos",
    name: "Brazil Santos",
    description: "Nutty and mellow with a creamy body, ideal for everyday brewing and milk drinks.",
    tastingNotes: ["Roasted peanut", "Milk chocolate", "Caramel"],
    roastLevel: "Medium",
    origin: "Brazil",
    category: "Single Origin",
    basePrice: 21,
    featured: false,
    rating: 4.6,
    reviews: 232,
    images: gallery(7, 3, 8),
    badge: "Everyday favorite",
    grindOptions: ["Whole bean", "Espresso", "Drip", "French press"],
    weightOptions: [250, 500, 1000],
    stock: 44,
  },
  {
    id: 16,
    slug: "panama-geisha-reserve",
    name: "Panama Geisha Reserve",
    description: "Rare and aromatic with jasmine, bergamot, and a delicate, tea-like sweetness.",
    tastingNotes: ["Jasmine", "Bergamot", "Peach tea"],
    roastLevel: "Light",
    origin: "Panama",
    category: "Single Origin",
    basePrice: 40,
    featured: false,
    rating: 4.9,
    reviews: 64,
    images: gallery(0, 4, 6),
    badge: "Limited release",
    grindOptions: ["Whole bean", "Pour over"],
    weightOptions: [250],
    stock: 6,
  },
  {
    id: 17,
    slug: "burundi-kayanza",
    name: "Burundi Kayanza",
    description: "Juicy and vibrant with blackcurrant, cane sugar, and a lingering citrus finish.",
    tastingNotes: ["Blackcurrant", "Cane sugar", "Lemon zest"],
    roastLevel: "Light",
    origin: "Burundi",
    category: "Single Origin",
    basePrice: 29,
    featured: false,
    rating: 4.7,
    reviews: 88,
    images: gallery(6, 0, 1),
    grindOptions: ["Whole bean", "Pour over", "Drip"],
    weightOptions: [250, 500],
    stock: 15,
  },
  {
    id: 18,
    slug: "honduras-marcala",
    name: "Honduras Marcala",
    description: "Smooth and sweet with red apple, toasted hazelnut, and a soft cocoa finish.",
    tastingNotes: ["Red apple", "Hazelnut", "Cocoa"],
    roastLevel: "Medium",
    origin: "Honduras",
    category: "Single Origin",
    basePrice: 23,
    featured: false,
    rating: 4.6,
    reviews: 110,
    images: gallery(1, 7, 4),
    grindOptions: ["Whole bean", "Drip", "Pour over"],
    weightOptions: [250, 500, 1000],
    stock: 33,
  },
  {
    id: 19,
    slug: "el-salvador-pacamara",
    name: "El Salvador Pacamara",
    description: "Full and syrupy with tropical fruit, brown sugar, and a rounded, sweet finish.",
    tastingNotes: ["Mango", "Brown sugar", "Dark cherry"],
    roastLevel: "Medium",
    origin: "El Salvador",
    category: "Single Origin",
    basePrice: 30,
    featured: false,
    rating: 4.8,
    reviews: 92,
    images: gallery(4, 6, 3),
    grindOptions: ["Whole bean", "Pour over", "French press"],
    weightOptions: [250, 500],
    stock: 13,
  },
  {
    id: 20,
    slug: "nicaragua-jinotega",
    name: "Nicaragua Jinotega",
    description: "Gentle and balanced with soft citrus, almond, and a clean, sweet aftertaste.",
    tastingNotes: ["Almond", "Tangerine", "Praline"],
    roastLevel: "Medium",
    origin: "Nicaragua",
    category: "Single Origin",
    basePrice: 25,
    featured: false,
    rating: 4.6,
    reviews: 101,
    images: gallery(7, 1, 8),
    grindOptions: ["Whole bean", "Drip", "Espresso"],
    weightOptions: [250, 500, 1000],
    stock: 27,
  },
  {
    id: 21,
    slug: "yemen-mocha-matari",
    name: "Yemen Mocha Matari",
    description: "Wild and complex with dried fruit, spice, and a wine-like, chocolatey finish.",
    tastingNotes: ["Dried fig", "Baking spice", "Dark chocolate"],
    roastLevel: "Dark",
    origin: "Yemen",
    category: "Single Origin",
    basePrice: 38,
    featured: false,
    rating: 4.8,
    reviews: 58,
    images: gallery(3, 4, 2),
    badge: "Rare find",
    grindOptions: ["Whole bean", "French press", "Espresso"],
    weightOptions: [250, 500],
    stock: 8,
  },
  {
    id: 22,
    slug: "tanzania-peaberry",
    name: "Tanzania Peaberry",
    description: "Bright and lively with blackberry, citrus, and a crisp, wine-like acidity.",
    tastingNotes: ["Blackberry", "Lime", "Brown sugar"],
    roastLevel: "Light",
    origin: "Tanzania",
    category: "Single Origin",
    basePrice: 28,
    featured: false,
    rating: 4.7,
    reviews: 84,
    images: gallery(0, 1, 6),
    grindOptions: ["Whole bean", "Pour over", "Drip"],
    weightOptions: [250, 500],
    stock: 17,
  },
  {
    id: 23,
    slug: "monsooned-malabar",
    name: "Monsooned Malabar",
    description: "Low-acid and earthy with a heavy body, warm spice, and toasted cedar sweetness.",
    tastingNotes: ["Cedar", "Warm spice", "Dark chocolate"],
    roastLevel: "Dark",
    origin: "India",
    category: "Single Origin",
    basePrice: 24,
    featured: false,
    rating: 4.5,
    reviews: 134,
    images: gallery(3, 8, 4),
    grindOptions: ["Whole bean", "French press", "Espresso"],
    weightOptions: [250, 500, 1000],
    stock: 25,
  },
  {
    id: 24,
    slug: "papua-new-guinea-sigri",
    name: "Papua New Guinea Sigri",
    description: "Syrupy and fruity with tropical notes, gentle spice, and a smooth cocoa finish.",
    tastingNotes: ["Papaya", "Cinnamon", "Cocoa"],
    roastLevel: "Medium",
    origin: "Papua New Guinea",
    category: "Single Origin",
    basePrice: 26,
    featured: false,
    rating: 4.6,
    reviews: 72,
    images: gallery(2, 7, 1),
    grindOptions: ["Whole bean", "Pour over", "French press"],
    weightOptions: [250, 500],
    stock: 21,
  },
  {
    id: 25,
    slug: "mexico-chiapas",
    name: "Mexico Chiapas",
    description: "Soft and approachable with toasted nuts, cocoa, and a lightly sweet finish.",
    tastingNotes: ["Toasted walnut", "Cocoa", "Vanilla"],
    roastLevel: "Medium",
    origin: "Mexico",
    category: "Single Origin",
    basePrice: 22,
    featured: false,
    rating: 4.5,
    reviews: 158,
    images: gallery(8, 7, 5),
    grindOptions: ["Whole bean", "Drip", "Espresso", "French press"],
    weightOptions: [250, 500, 1000],
    stock: 38,
  },
  {
    id: 26,
    slug: "bolivia-caranavi",
    name: "Bolivia Caranavi",
    description: "Clean and floral with orange blossom, green apple, and a silky, sweet finish.",
    tastingNotes: ["Orange blossom", "Green apple", "Honey"],
    roastLevel: "Light",
    origin: "Bolivia",
    category: "Single Origin",
    basePrice: 27,
    featured: false,
    rating: 4.7,
    reviews: 66,
    images: gallery(6, 4, 0),
    grindOptions: ["Whole bean", "Pour over"],
    weightOptions: [250, 500],
    stock: 16,
  },
  {
    id: 27,
    slug: "ecuador-loja",
    name: "Ecuador Loja",
    description: "Fragrant and rounded with red berries, panela sweetness, and a gentle floral lift.",
    tastingNotes: ["Red berries", "Panela", "Rose"],
    roastLevel: "Medium",
    origin: "Ecuador",
    category: "Single Origin",
    basePrice: 28,
    featured: false,
    rating: 4.6,
    reviews: 54,
    images: gallery(1, 0, 7),
    grindOptions: ["Whole bean", "Pour over", "Drip"],
    weightOptions: [250, 500],
    stock: 14,
  },

  // ---------------------------------------------------------------------------
  // New blends
  // ---------------------------------------------------------------------------
  {
    id: 28,
    slug: "sunrise-breakfast-blend",
    name: "Sunrise Breakfast Blend",
    description: "Bright, crisp, and easy-drinking with citrus, honey, and a clean morning finish.",
    tastingNotes: ["Citrus", "Honey", "Toasted grain"],
    roastLevel: "Light",
    origin: "Blend",
    category: "Blends",
    basePrice: 20,
    featured: false,
    rating: 4.6,
    reviews: 288,
    images: gallery(7, 0, 6),
    badge: "Crowd pleaser",
    grindOptions: ["Whole bean", "Drip", "Pour over"],
    weightOptions: [250, 500, 1000],
    stock: 46,
  },
  {
    id: 29,
    slug: "brewcraft-house-blend",
    name: "BrewCraft House Blend",
    description: "Our signature everyday cup: chocolatey, balanced, and comfortingly smooth.",
    tastingNotes: ["Milk chocolate", "Toasted nut", "Caramel"],
    roastLevel: "Medium",
    origin: "Blend",
    category: "Blends",
    basePrice: 21,
    featured: false,
    rating: 4.8,
    reviews: 342,
    images: gallery(1, 4, 8),
    badge: "House favorite",
    grindOptions: ["Whole bean", "Drip", "French press", "Pour over"],
    weightOptions: [250, 500, 1000],
    stock: 50,
  },
  {
    id: 30,
    slug: "midnight-blend",
    name: "Midnight Blend",
    description: "Deep and velvety with dark cocoa, roasted almond, and a long, smoky finish.",
    tastingNotes: ["Dark cocoa", "Roasted almond", "Smoke"],
    roastLevel: "Dark",
    origin: "Blend",
    category: "Blends",
    basePrice: 24,
    featured: false,
    rating: 4.7,
    reviews: 176,
    images: gallery(3, 2, 5),
    grindOptions: ["Whole bean", "French press", "Espresso", "Drip"],
    weightOptions: [250, 500, 1000],
    stock: 29,
  },
  {
    id: 31,
    slug: "cold-brew-reserve-blend",
    name: "Cold Brew Reserve Blend",
    description: "Built for slow steeping: smooth, low-acid, and naturally sweet over ice.",
    tastingNotes: ["Chocolate", "Brown sugar", "Baked plum"],
    roastLevel: "Medium",
    origin: "Blend",
    category: "Blends",
    basePrice: 23,
    featured: false,
    rating: 4.8,
    reviews: 204,
    images: gallery(8, 1, 3),
    badge: "Cold brew pick",
    grindOptions: ["Whole bean", "French press", "Drip"],
    weightOptions: [500, 1000],
    stock: 32,
  },
  {
    id: 32,
    slug: "holiday-hearth-blend",
    name: "Holiday Hearth Blend",
    description: "Warm and cozy with cinnamon, baked apple, and caramelized sugar.",
    tastingNotes: ["Cinnamon", "Baked apple", "Caramel"],
    roastLevel: "Medium",
    origin: "Blend",
    category: "Blends",
    basePrice: 24,
    featured: false,
    rating: 4.6,
    reviews: 120,
    images: gallery(5, 7, 4),
    badge: "Seasonal",
    grindOptions: ["Whole bean", "Drip"],
    weightOptions: [250, 500],
    stock: 24,
  },
  {
    id: 33,
    slug: "hazelnut-cream-blend",
    name: "Hazelnut Cream Blend",
    description: "Buttery hazelnut and soft vanilla over a smooth, mellow cup.",
    tastingNotes: ["Hazelnut", "Vanilla", "Cream"],
    roastLevel: "Medium",
    origin: "Blend",
    category: "Blends",
    basePrice: 22,
    featured: false,
    rating: 4.5,
    reviews: 190,
    images: gallery(5, 8, 7),
    grindOptions: ["Whole bean", "Drip", "Espresso"],
    weightOptions: [250, 500, 1000],
    stock: 36,
  },
  {
    id: 34,
    slug: "golden-hour-blend",
    name: "Golden Hour Blend",
    description: "Sweet and fruit-forward with stone fruit, honey, and a gentle citrus finish.",
    tastingNotes: ["Apricot", "Honey", "Orange peel"],
    roastLevel: "Light",
    origin: "Blend",
    category: "Blends",
    basePrice: 23,
    featured: false,
    rating: 4.7,
    reviews: 98,
    images: gallery(0, 7, 6),
    grindOptions: ["Whole bean", "Pour over", "Drip"],
    weightOptions: [250, 500],
    stock: 22,
  },

  // ---------------------------------------------------------------------------
  // New espresso
  // ---------------------------------------------------------------------------
  {
    id: 35,
    slug: "crema-classico",
    name: "Crema Classico",
    description: "Classic Italian-style espresso with thick crema, cocoa, and toasted hazelnut.",
    tastingNotes: ["Cocoa", "Toasted hazelnut", "Caramel"],
    roastLevel: "Espresso",
    origin: "Blend",
    category: "Espresso",
    basePrice: 26,
    featured: false,
    rating: 4.7,
    reviews: 214,
    images: gallery(5, 2, 3),
    grindOptions: ["Whole bean", "Espresso"],
    weightOptions: [250, 500, 1000],
    stock: 34,
  },
  {
    id: 36,
    slug: "ristretto-noir",
    name: "Ristretto Noir",
    description: "Concentrated and intense with bittersweet chocolate, black cherry, and a lasting finish.",
    tastingNotes: ["Bittersweet chocolate", "Black cherry", "Molasses"],
    roastLevel: "Espresso",
    origin: "Blend",
    category: "Espresso",
    basePrice: 29,
    featured: false,
    rating: 4.8,
    reviews: 132,
    images: gallery(2, 3, 5),
    badge: "Bold",
    grindOptions: ["Whole bean", "Espresso"],
    weightOptions: [250, 500],
    stock: 18,
  },
  {
    id: 37,
    slug: "napoli-espresso",
    name: "Napoli Espresso",
    description: "Southern Italian style: powerful, smoky, and syrupy with a bittersweet edge.",
    tastingNotes: ["Dark chocolate", "Roasted nuts", "Smoke"],
    roastLevel: "Dark",
    origin: "Italy",
    category: "Espresso",
    basePrice: 25,
    featured: false,
    rating: 4.6,
    reviews: 148,
    images: gallery(3, 5, 8),
    grindOptions: ["Whole bean", "Espresso", "French press"],
    weightOptions: [250, 500, 1000],
    stock: 26,
  },
  {
    id: 38,
    slug: "latte-lover-espresso",
    name: "Latte Lover Espresso",
    description: "Sweet, low-acid, and built for milk drinks with caramel and chocolate depth.",
    tastingNotes: ["Caramel", "Milk chocolate", "Toasted almond"],
    roastLevel: "Espresso",
    origin: "Blend",
    category: "Espresso",
    basePrice: 24,
    featured: false,
    rating: 4.8,
    reviews: 246,
    images: gallery(5, 4, 7),
    badge: "Latte favorite",
    grindOptions: ["Whole bean", "Espresso", "Drip"],
    weightOptions: [250, 500, 1000],
    stock: 40,
  },
  {
    id: 39,
    slug: "ethiopia-natural-espresso",
    name: "Ethiopia Natural Espresso",
    description: "Fruit-forward espresso with blueberry jam, floral aroma, and a syrupy body.",
    tastingNotes: ["Blueberry jam", "Jasmine", "Dark sugar"],
    roastLevel: "Espresso",
    origin: "Ethiopia",
    category: "Espresso",
    basePrice: 31,
    featured: false,
    rating: 4.7,
    reviews: 86,
    images: gallery(2, 0, 5),
    grindOptions: ["Whole bean", "Espresso"],
    weightOptions: [250, 500],
    stock: 12,
  },

  // ---------------------------------------------------------------------------
  // New decaf
  // ---------------------------------------------------------------------------
  {
    id: 40,
    slug: "colombia-sugarcane-decaf",
    name: "Colombia Sugarcane Decaf",
    description: "Naturally decaffeinated with caramel sweetness, red apple, and a smooth finish.",
    tastingNotes: ["Caramel", "Red apple", "Cocoa"],
    roastLevel: "Medium",
    origin: "Colombia",
    category: "Decaf",
    basePrice: 26,
    featured: false,
    rating: 4.6,
    reviews: 118,
    images: gallery(8, 1, 4),
    grindOptions: ["Whole bean", "Drip", "French press", "Pour over"],
    weightOptions: [250, 500, 1000],
    stock: 23,
  },
  {
    id: 41,
    slug: "decaf-espresso",
    name: "Decaf Espresso",
    description: "All the body and crema of espresso with rich cocoa, toasted almond, and no jitters.",
    tastingNotes: ["Cocoa", "Toasted almond", "Brown sugar"],
    roastLevel: "Espresso",
    origin: "Blend",
    category: "Decaf",
    basePrice: 27,
    featured: false,
    rating: 4.5,
    reviews: 74,
    images: gallery(2, 8, 5),
    grindOptions: ["Whole bean", "Espresso"],
    weightOptions: [250, 500],
    stock: 19,
  },
  {
    id: 42,
    slug: "evening-decaf-blend",
    name: "Evening Decaf Blend",
    description: "A cozy after-dinner cup with toffee, hazelnut, and gentle dark chocolate.",
    tastingNotes: ["Toffee", "Hazelnut", "Dark chocolate"],
    roastLevel: "Medium",
    origin: "Blend",
    category: "Decaf",
    basePrice: 22,
    featured: false,
    rating: 4.6,
    reviews: 92,
    images: gallery(7, 3, 4),
    grindOptions: ["Whole bean", "Drip", "French press"],
    weightOptions: [250, 500, 1000],
    stock: 28,
  },
];

export const featuredProducts = products.filter((product) => product.featured);

export const testimonials = [
  { name: "Ava M.", role: "Product designer", quote: "The flavor clarity is exceptional. Every cup feels considered and premium.", rating: 5 },
  { name: "Theo R.", role: "Freelance writer", quote: "It tastes like a café ritual without the busy rush. The delivery and freshness are excellent.", rating: 5 },
  { name: "Nina S.", role: "Creative lead", quote: "The single origins really do have their own story. I keep coming back for the Ethiopian roast.", rating: 5 },
];

export const brewingMethods: BrewingMethod[] = [
  { title: "Pour over", description: "Bright, floral clarity with slower extraction and a delicate finish.", icon: Coffee },
  { title: "French press", description: "A full-bodied, textured cup with soft oils and a rich, sweet body.", icon: FlaskConical },
  { title: "Espresso", description: "Thick, sweet, and concentrated for lattes, cappuccinos, and short pours.", icon: Sunset },
  { title: "Cold brew", description: "Smooth, mellow, and naturally sweet for slow afternoons and warm days.", icon: Waves },
];

export const formatPrice = (value: number) =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);

export const getProductBySlug = (slug: string) => products.find((product) => product.slug === slug);

export const relatedProducts = (slug: string) =>
  products.filter((product) => product.slug !== slug).slice(0, 4);